### ISSUE TITLE
Pc Gen app

### ISSUE THREAD

**Issue by snoopyreed79** [dysfunctional-apps/character-sheet-importer#1]
This app works really well just a small thing that I found with a person that is a spell user spell levels 1 and up work every time you use a spell it subtracts correctly but the 0 level spell stays the same

**Comment by dysfunctional-apps** [comment]
@snoopyreed79, In Pathfinder, 0 level spells do not are cantrips/orisons and therefore can be cast numerous times - therefore the count does not decrement.  I am happy to be corrected if my understanding is wrong.

**Comment by snoopyreed79** [comment]
in d&d 3rd edition I was always under the impression that a 0 level spell
was like all other spell you were only able to cast Say for sorcerer 4, 0
level spell I looked and I could have missed something but that is the way
i reed it to. I can't find anything in my players handbook on cantrips  on
that note it you could point me to that information I would appreciate it.
Thanks for your insight,
Snoopy

**Comment by dysfunctional-apps** [comment]
@snoopyreed79 Sorry, I missed that you had replied - I will look into this

**Comment by snoopyreed79** [comment]
that's ok I just am happy someone even responded to my email in the first
place lol thanks for looking into it

**Comment by dysfunctional-apps** [comment]
https://rpg.stackexchange.com/questions/19083/do-all-spellcasting-classes-get-unlimited-cantrips

Question:

_"Do all spellcasting classes get unlimited cantrips?

I at least know that Wizards get to use level-0 spells an unlimited number of times a day, but is this a class feature, or are all cantrips unlimited use? I ask this because some spontaneous spellcasting classes still have a limited number of slots for level 0 spells, even if they aren't capable of learning that many spells of that level, and was wondering if they are limited use for those classes."_

Answer:

_"No, and wizards don't either.

Wizards learn all cantrips available to them automatically, but they are restricted by their prepared spell slots per day in cantrips as with every other level of spell. This slots-per-day limit is true of all other casters (spontaneous or prepared-type) with access to 0-level spells of any sort; the advantage wizards get is only in knowing all of the cantrips, not in being able to use them as often as they like.

[NB: Both Pathfinder and 5e do implement unlimited cantrips, which may be a source of confusion.]"_

**Comment by snoopyreed79** [comment]
that clears that up the app is used as a general app to cover all character
sheets. In that case is there a way to keep track of the 0 level spells to
tell how many times you use it.  The reason I ask is I play with my boys
and I sometimes run games for there friends and they all use this app you
know how kids are when you get and group of them together. It is just a
question I use pen and paper to control it just looking for other was to
help

On Sep 5, 2017 3:27 AM, "Lee Jackson" <notifications@github.com> wrote:

https://rpg.stackexchange.com/questions/19083/do-all-
spellcasting-classes-get-unlimited-cantrips

Question:

_"Do all spellcasting classes get unlimited cantrips?

I at least know that Wizards get to use level-0 spells an unlimited number
of times a day, but is this a class feature, or are all cantrips unlimited
use? I ask this because some spontaneous spellcasting classes still have a
limited number of slots for level 0 spells, even if they aren't capable of
learning that many spells of that level, and was wondering if they are
limited use for those classes."_

Answer:

_"No, and wizards don't either.

Wizards learn all cantrips available to them automatically, but they are
restricted by their prepared spell slots per day in cantrips as with every
other level of spell. This slots-per-day limit is true of all other casters
(spontaneous or prepared-type) with access to 0-level spells of any sort;
the advantage wizards get is only in knowing all of the cantrips, not in
being able to use them as often as they like.

[NB: Both Pathfinder and 5e do implement unlimited cantrips, which may be a
source of confusion.]"_

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dysfunctional-apps/character-sheet-importer/issues/1#issuecomment-327094253>,
or mute the thread

**Comment by dysfunctional-apps** [comment]
Basically the app started out just as a thing for me when I played as I couldn't find an app that did what I wanted, so it was created purely with Pathfinder in mind (as that is all I've ever played). Since making it available to everyone else I have tried to make it accommodate 3/3.5 as most of it "just works", so these things only get updated when they are highlighted to me (much in the way you have), so that's why I put in the store listing that Pathfinder characters are the only officially supported imports but I am quite happy to make this change for you.  The main reason I haven't tried to implement 100% support is because I haven't played other versions and don't want to mess it up.

I'll let you know when the change has been made.

Thanks for your patience

**Comment by snoopyreed79** [comment]
thanks I am very happy with how you are willing to make changes to this
useful app I am glad that you are even talking to me a lot of people who
make apps just kinda let questions like mine go to the wayside and just
collect the money.  I thank you again for the response and research you did
for this question.

**Comment by dysfunctional-apps** [comment]
No worries, as I say it was created to be useful, the money is used purely to pay for dev devices and android emulators to support development so I'm not just in it for the money

**Comment by dysfunctional-apps** [comment]
@snoopyreed79 are you using the hero lab or pcgen version of the app?

**Comment by dysfunctional-apps** [comment]
@snoopyreed79 just to let you know I've published an update to hopefully resolve this issue - you will however need to reimport any characters that are affected - it can take a few hours for update to appear in all regions

Thanks for getting in touch

Lee
